name: Generate Documentation

on:
  push:
    branches: [ main, develop ]
    paths:
      - '**/*.sh'
      - 'examples/**'
      - 'LinuxTools/**'
      - 'ToolboxCore/**'
      - 'ToolboxTools/**'
      - 'scripts/**'
  pull_request:
    branches: [ main ]
    paths:
      - '**/*.sh'
      - 'examples/**'
      - 'LinuxTools/**'
      - 'ToolboxCore/**'
      - 'ToolboxTools/**'
      - 'scripts/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y jq
    
    - name: Make documentation generator executable
      run: |
        chmod +x scripts/generate_documentation.sh
        chmod +x scripts/extract_script_metadata.sh
    
    - name: Generate documentation
      run: |
        ./scripts/generate_documentation.sh
    
    - name: Check for documentation changes
      id: verify-changed-files
      run: |
        if [ -n "$(git status --porcelain docs/)" ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "changed=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Commit documentation changes
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: |
        git add docs/
        git commit -m "📚 Auto-update documentation from script headers
        
        - Updated script documentation
        - Generated table of contents
        - Extracted metadata from headers
        - Organized by categories
        
        🤖 Generated with Claude Code
        
        Co-Authored-By: Claude <noreply@anthropic.com>" || exit 0
    
    - name: Push documentation changes
      if: steps.verify-changed-files.outputs.changed == 'true'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}